version: '3'

services:
    db:
        image: postgres
    migration:
        build: .
        command: 
        volumes:
            - .:/usr/src/app
        depends_on:
            - db
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: django
            POSTGRES_PASSWORD: password
    web:
        build: .
        command: 
        volumes:
            - .:/usr/src/app
        ports:
            - "8000:5000"
        depends_on:
            - db
            - migration
